name: Go

on:
  push:
    branches: [ master ]
    tags:
      - '*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ master ]

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest

    steps:
      - name: Install libsensors4-dev (needed for gosensors testing)
        run: sudo apt-get install -y libsensors4-dev

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1.1.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          platforms: 'linux/amd64, linux/arm64'
          package: ''
          name: 'fan2go'
          compress: 'false'
          dest: 'dist'

      - name: Generate build files
        run: go build -o ./dist/fan2go-linux-amd64 main.go
        #if: startsWith(github.ref, 'refs/tags/')

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/fan2go-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
